POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
  "title": "kokeilu title",
  "author": "kokeilu author",
  "url": "http://kokeilu.test",
  "likes": "",
  "userId": "69d50a96b425ecb954989770"
}